AWSTemplateFormatVersion: "2010-09-09"
Description: "To enable access to S3 buckets from Private Subnet, using Lambda function"

Parameters:
  Vpc:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /VPC

Mappings: 
  subnet:
    cidrblock:
      publicip: 172.20.1.0/24
      publicip2: 172.20.2.0/24
      privateip: 172.20.11.0/24
      privateip2: 172.20.12.0/24
    region:
      az1: ap-southeast-2a
      az2: ap-southeast-2b

Resources:

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap ["subnet", "cidrblock", "publicip"]
      AvailabilityZone: !FindInMap ["subnet", "region", "az1"]
      Tags:
        - Key: Subnet
          Value: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap ["subnet", "cidrblock", "publicip2"]
      AvailabilityZone: !FindInMap ["subnet", "region", "az2"]
      Tags:
        - Key: Subnet
          Value: PublicSubnet2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap ["subnet", "cidrblock", "privateip"]
      AvailabilityZone: !FindInMap ["subnet", "region", "az1"]
      Tags:
        - Key: Subnet
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap ["subnet", "cidrblock", "privateip2"]
      AvailabilityZone: !FindInMap ["subnet", "region", "az2"]
      Tags:
        - Key: Subnet
          Value: PrivateSubnet2

  SSMPublicSubnet:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PublicSubnet1"
      Type: String
      Value: !Ref PublicSubnet1

  SSMPublicSubnet2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PublicSubnet2"
      Type: String
      Value: !Ref PublicSubnet2

  SSMPrivateSubnet:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateSubnet1"
      Type: String
      Value: !Ref PrivateSubnet1

  SSMPrivateSubnet2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateSubnet2"
      Type: String
      Value: !Ref PrivateSubnet2

