AWSTemplateFormatVersion: "2010-09-09"
Description: "To enable access to S3 buckets from Private Subnet, using Lambda function"

Parameters:
  Vpc:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /VPC
  PrivateSubnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet1
  PrivateSubnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet2

  # PrivateEC2InstanceIAMRole:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /PrivateEC2InstanceIAMRole

Resources:
  #*************RouteTable***********
  PrivateRoutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  # *************NAT Gateway*************
  # NatEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: NatGateway

  PrivateRouteToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRoutetable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
  
  #*************Subnet Route Table Association*************
  # Associate the subnets with the route table
  AssoPrivSub1RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRoutetable

  AssoPrivSub2RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRoutetable


  #*************SSM*************
  SSMPrivRoutetable:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateRouteTable"
      Type: String
      Value: !Ref PrivateRoutetable
