AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Public EC2 Instance with CloudWatch Agent and SSM Agent"

Parameters:
  PublicSubnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicSubnet1
  PublicSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2SecurityGroup
  PublicKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicKeypair
  PublicEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2InstanceProfile
  CWAgentConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CWAgentConfig
  EC2ScriptsSSM:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /EC2ScriptsSSM

Mappings:
  instance:
    region:
      az1: ap-southeast-2a
      az2: ap-southeast-2c
      
Resources:
  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap ["instance", "region", "az1"]
      ImageId: ami-03af661583141dc27
      # ami-03af661583141dc27 # Windows Server 2025 Base
      InstanceType: t3.micro # Supports UEFI
      KeyName: !Ref PublicKeyPair
      VolumeId: !Ref PublicVolume
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet1
          GroupSet:
            - !Ref PublicSecurityGroup
      IamInstanceProfile: !Ref PublicEC2InstanceProfile
      # CW Agent Profiles Settings
      UserData:   
        !Base64
          Fn::Sub:
            - "${EC2Script}"
            - EC2Script: !Ref EC2ScriptsSSM
              ssmkey: !Ref CWAgentConfig
      Tags:
        - Key: Name
          Value: PublicEC2Instance

  # EBS Volume for public EC2 Instance
  PublicEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !FindInMap ["instance", "region", "az1"]
      Size: 30
      VolumeType: gp2 # General Purpose SSD
      Tags:
        - Key: Name
          Value: PublicEBSVolume

  # SSM Parameter for EC2 Instance
  SSMPublicEC2Instance:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PublicEC2Instance"
      Type: String
      Value: !Ref PublicInstance