AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for Plan4'

Resources:
  Plan4DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: plan4-dynamodb-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: name
          AttributeType: S
        - AttributeName: description
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true