AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Public EC2 Instance with CloudWatch Agent and SSM Agent"

Parameters:
  PublicSubnet:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicSubnet1
  PublicSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2SecurityGroup
  PublicKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicKeypair
  PublicEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2InstanceProfile
  CWLogsConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CWAgentConfig

Mappings:
  instance:
    region:
      az1: ap-southeast-2a
      az2: ap-southeast-2c
      
Resources:
  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap ["instance", "region", "az1"]
      ImageId: ami-0f14d0949beaa4f7e
      # ami-024781a6c1dcb2253 #Windows Server
      InstanceType: t3.micro # Supports UEFI
      KeyName: !Ref PublicKeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref PublicSecurityGroup
      IamInstanceProfile: !Ref PublicEC2InstanceProfile
      # CW Agent Profiles Settings
      UserData: !Base64 
        Fn::Sub:
          - |
            <script>
            # Install CloudWatch Agent and set up using SSM Parameter Store

            mkdir C:\Downloads\Amazon\AmazonCloudWatchAgent
            powershell -Command "(New-Object Net.WebClient).DownloadFile('https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi','C:\Downloads\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.msi')"
            C:\Downloads\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.msi
            powershell -Command "C:\'Program Files'\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c ssm:${ssmkey} -s"
            cfn-init.exe -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} --configsets default
            cfn-signal.exe -e %errorlevel% --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
            
            # Download and install SSM Agent
            Invoke-WebRequest -Uri https://s3.amazonaws.com/amazon-ssm-${AWS::Region}/latest/windows_amd64/AmazonSSMAgentSetup.exe -OutFile C:\Temp\AmazonSSMAgentSetup.exe
            Start-Process -FilePath C:\Temp\AmazonSSMAgentSetup.exe -ArgumentList "/quiet" -Wait
            
            # Install AWS CLI v2
            curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
            msiexec.exe /i AWSCLIV2.msi /qn
            </script>
          - ssmkey: !Ref CWLogsConfig
      Tags:
        - Key: Name
          Value: PublicEC2Instance

  # SSM Parameter for EC2 Instance
  SSMPublicEC2Instance:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PublicEC2Instance"
      Type: String
      Value: !Ref PublicInstance