AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Private EC2 Instance with CloudWatch Agent and SSM Agent"

Parameters:
  PrivateSubnet:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet1
  PrivateSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateEC2SecurityGroup
  PrivateKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateKeypair
  PrivateEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateEC2InstanceProfile
  CWAgentConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CWAgentConfig
  EC2ScriptsSSM:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /EC2ScriptsSSM

Mappings:
  instance:
    region:
      az1: ap-southeast-2a
      az2: ap-southeast-2c
      
Resources:
  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap ["instance", "region", "az1"]
      ImageId: ami-0f14d0949beaa4f7e
      # ami-0f14d0949beaa4f7e #Windows Server
      InstanceType: t3.micro # Supports UEFI
      KeyName: !Ref PrivateKeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PrivateSubnet
          GroupSet:
            - !Ref PrivateSecurityGroup
      IamInstanceProfile: !Ref PrivateEC2InstanceProfile
      UserData:   
        !Base64
          Fn::Sub:
            - "${EC2Script}"
            - EC2Script: !Ref EC2ScriptsSSM
              ssmkey: !Ref CWAgentConfig
      Tags:
        - Key: Name
          Value: PrivateEC2Instance

  # SSM Parameter for EC2 Instance
  SSMPrivateEC2Instance:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateEC2Instance"
      Type: String
      Value: !Ref PrivateInstance