AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Fleet with Launch Template"

Parameters:
  PublicSubnet:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicSubnet1
  PublicSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2SecurityGroup
  PublicKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicKeypair
  PublicEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2InstanceProfile

Resources:
  
  PublicEC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: "ami-08b26451ed3e0ef79"
        InstanceType: "t3.micro"
        SecurityGroupIds:
          - !Ref PublicSecurityGroup
        KeyName: !Ref PublicKeyPair
        IamInstanceProfile: !Ref PublicEC2InstanceProfile
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: PatchGroup
                Value: WindowsFleet

  PublicEC2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet
      LaunchTemplate:
        LaunchTemplateId: !Ref PublicEC2LaunchTemplate
        Version: !GetAtt PublicEC2LaunchTemplate.LatestVersionNumber
      MinSize: 3 # Number of instances to launch
      MaxSize: 3
      DesiredCapacity: 3
      Tags:
        - Key: PatchGroup
          Value: WindowsFleet
          PropagateAtLaunch: true
