AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Fleet with Launch Template"

Parameters:
  PublicSubnet:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicSubnet1
  PublicSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2SecurityGroup
  PublicKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicKeypair
  PublicEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2InstanceProfile

Resources:
  # After creating the public EC2 instance and use new AMI from it, update the ImageId below
  PublicEC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-08b26451ed3e0ef79"
      InstanceType: "t3.micro"
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      KeyName: !Ref PublicKeyPair
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: PatchGroup
          Value: WindowsFleet
      IamInstanceProfile: !Ref PublicEC2InstanceProfile