AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  # For CWAgent Setting
  CWAgentConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CWAgentConfig
      Type: String
      Value: |
        {
          "agent": {
            "metrics_collection_interval": 60,
            "run_as_user": "System"
          },
          "metrics": {
            "metrics_collected": {
              "CPU": {
                "measurement": [
                  {"name": "% Idle Time", "unit": "Percent"},
                  {"name": "% Interrupt Time", "unit": "Percent"},
                  {"name": "% User Time", "unit": "Percent"},
                  {"name": "% Processor Time", "unit": "Percent"}
                ],
                "resources": ["*"],
                "totalcpu": true
              },
              "Memory": {
                "measurement": [
                  {"name": "% Committed Bytes In Use", "unit": "Percent"},
                  {"name": "Available Bytes", "unit": "Bytes"},
                  {"name": "Committed Bytes", "unit": "Bytes"}
                ]
              },
              "LogicalDisk": {
                "measurement": [
                  {"name": "% Free Space", "unit": "Percent"},
                  {"name": "Free Megabytes", "unit": "Megabytes"}
                ],
                "resources": ["*"]
              }
            },
            "aggregation_dimensions": [["InstanceId"]]
          },
          "logs": {
            "logs_collected": {
              "windows_events": {
                "collect_list": [
                  {
                    "event_name": "System",
                    "event_levels": ["INFORMATION", "WARNING", "ERROR", "CRITICAL"],
                    "log_group_name": "/aws/ec2/windows/system",
                    "log_stream_name": "{instance_id}"
                  },
                  {
                    "event_name": "Application",
                    "event_levels": ["INFORMATION", "WARNING", "ERROR", "CRITICAL"],
                    "log_group_name": "/aws/ec2/windows/application",
                    "log_stream_name": "{instance_id}"
                  }
                ]
              }
            }
          }
        }