AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "AWS CloudFormation template to create EC2 Key Pairs."

Parameters:
  PublicEC2Role:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PublicEC2InstanceIAMRole
  PrivateEC2Role:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateEC2InstanceIAMRole

Resources:
  PublicEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref PublicEC2Role

  PrivateEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref PrivateEC2Role

  SSMPublicEC2Instanceprofile:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PublicEC2InstanceProfile"
      Type: String
      Value: !Ref PublicEC2InstanceProfile

  SSMPrivateEC2Instanceprofile:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateEC2InstanceProfile"
      Type: String
      Value: !Ref PrivateEC2InstanceProfile