AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM Role for S3 Replication"

Resources:
  # IAM Role for S3 Replication
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "S3ReplicationRole-Destination"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ReadSourceBucket
                Effect: Allow
                Action:
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:ListBucket
                  - s3:GetBucketVersioning
                Resource:
                  - 'arn:aws:s3:::lambda-apse2-bucket1313'
                  - 'arn:aws:s3:::lambda-apse2-bucket1313/*'
                  - 'arn:aws:s3:::web-apse2-bucket1313'
                  - 'arn:aws:s3:::web-apse2-bucket1313/*'

              - Sid: WriteIntoDestinationBucket
                Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - 'arn:aws:s3:::lambda-apse1-backup-bucket1313'
                  - 'arn:aws:s3:::lambda-apse1-backup-bucket1313/*'
                  - 'arn:aws:s3:::web-apne1-backup-bucket1313'
                  - 'arn:aws:s3:::web-apne1-backup-bucket1313/*'

  # Store the replication role ARN in SSM Parameter Store
  S3RoleSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "S3ReplicationRole"
      Type: String
      Value: !GetAtt S3ReplicationRole.Arn

