AWSTemplateFormatVersion: "2010-09-09"
Description: "s3 replication bucket in apne1 region"

Parameters:
  ReplicationRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /S3ReplicationRole

Resources:
  # S3 Bucket
  DestinationS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "lambda-apne1-backup-bucket1313"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 30
            Transitions:
              - TransitionInDays: 15
                StorageClass: GLACIER

  # S3 Bucket Policy
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DestinationS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowReplicationFromSource
            Effect: Allow
            Principal:
              AWS: !Ref ReplicationRoleArn
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
            Resource:
              - !Sub 'arn:aws:s3:::${DestinationS3Bucket}'
              - !Sub 'arn:aws:s3:::${DestinationS3Bucket}/*'