AWSTemplateFormatVersion: "2010-09-09"
Description: "To enable access to S3 buckets from Private Subnet, using Lambda function"

Parameters:
  S3ReplicationRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /S3ReplicationRole
  LambdaExecutionRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /LambdaExecutionRole
  S3EndpointId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /S3EndpointId
  
Resources:
  # S3 Bucket for Lambda function
  lambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "lambda-apse2-bucket1313"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 30
            Transitions:
              - TransitionInDays: 15
                StorageClass: GLACIER
      ReplicationConfiguration:
        Role: !Ref S3ReplicationRoleArn
        Rules:
          - Id: ReplicateToTokyo
            Status: Enabled
            Destination:
              Bucket: 'arn:aws:s3:::lambda-apne1-backup-bucket1313'
              StorageClass: STANDARD

  lambdaS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref lambdaS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReplicationFromSource
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub arn:aws:iam::${AWS::AccountId}:role/S3ReplicationRole-Source
                - !Sub arn:aws:iam::${AWS::AccountId}:role/S3ReplicationRole-Destination
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${lambdaS3Bucket}" 
              - !Sub "arn:aws:s3:::${lambdaS3Bucket}/*"

          # permit only traffics from S3 Endpoint
          - Sid: AllowAccessFromLambda
            Effect: Allow
            Principal:
              AWS: !Ref LambdaExecutionRoleArn
            Action:
              - s3:GetObject
            Resource: 
              - !Sub "arn:aws:s3:::${lambdaS3Bucket}"
              - !Sub "arn:aws:s3:::${lambdaS3Bucket}/*"
            Condition:
              StringEquals:
                aws:SourceVpce: !Ref S3EndpointId

  lambdaS3BucketSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "LambdaS3BucketName"
      Type: String
      Value: !Ref lambdaS3Bucket