AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Private EC2 Instance with CloudWatch Agent and SSM Agent"

Parameters:
  PrivateSubnet:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet1
  PrivateSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateEC2SecurityGroup
  PrivateKeyPair:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateKeypair
  PrivateEC2InstanceProfile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateEC2InstanceProfile
  CWLogsConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CWAgentConfig

Mappings:
  instance:
    region:
      az1: ap-southeast-2a
      az2: ap-southeast-2c
      
Resources:
  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap ["instance", "region", "az1"]
      ImageId: ami-0f14d0949beaa4f7e
      # ami-0f14d0949beaa4f7e #Windows Server
      InstanceType: t3.micro # Supports UEFI
      KeyName: !Ref PrivateKeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PrivateSubnet
          GroupSet:
            - !Ref PrivateSecurityGroup
      IamInstanceProfile: !Ref PrivateEC2InstanceProfile
      UserData: !Base64 
        Fn::Sub:
          - |
            <script>
            # Install CloudWatch Agent

            mkdir C:\Downloads\Amazon\AmazonCloudWatchAgent
            powershell -Command "(New-Object Net.WebClient).DownloadFile('https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi','C:\Downloads\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.msi')"
            C:\Downloads\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.msi
            powershell -Command "C:\'Program Files'\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c ssm:${ssmkey} -s"
            cfn-init.exe -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} --configsets default
            cfn-signal.exe -e %errorlevel% --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
            
            # Download and install SSM Agent
            Invoke-WebRequest -Uri https://s3.amazonaws.com/amazon-ssm-${AWS::Region}/latest/windows_amd64/AmazonSSMAgentSetup.exe -OutFile C:\Temp\AmazonSSMAgentSetup.exe
            Start-Process -FilePath C:\Temp\AmazonSSMAgentSetup.exe -ArgumentList "/quiet" -Wait
            
            # Install AWS CLI v2
            curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
            msiexec.exe /i AWSCLIV2.msi /qn

            </script>
          - ssmkey: !Ref CWLogsConfig

  # SSM Parameter for EC2 Instance
  SSMPrivateEC2Instance:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateEC2Instance"
      Type: String
      Value: !Ref PrivateInstance