AWSTemplateFormatVersion: "2010-09-09"
Description: "To enable access to S3 buckets from Private Subnet, using Lambda function"

Parameters:
  Vpc:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /VPC
  PrivateSubnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet1
  PrivateSubnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateSubnet2
  PrivateRoutetable:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PrivateRouteTable
  LambdaExecutionRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /LambdaExecutionRole

  #*************Endpoint*************

Resources:
  # Access from Private Subnet and Lambda to S3
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - 's3:*'
            Resource: 'arn:aws:s3:::*'
            Condition:
              StringEquals:
                aws:SourceVpc: !Ref Vpc
          
      RouteTableIds:
        - !Ref PrivateRoutetable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref Vpc

  DynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 'dynamodb:*'
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceVpc: !Ref Vpc
      RouteTableIds:
        - !Ref PrivateRoutetable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcId: !Ref Vpc

  # SNS Endpoint
  SNSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sns'
      VpcId: !Ref Vpc
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroupIds:
        - "sg-09548281c14833ca7"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 'sns:*'
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceVpc: !Ref Vpc
      PrivateDnsEnabled: true

  SSMS3Endpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "S3EndpointId"
      Type: String
      Value: !Ref S3Endpoint

  SSMDynamoDBEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "DynamoDBEndpointId"
      Type: String
      Value: !Ref DynamoDBEndpoint

  SSMSNSEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "SNSEndpointId"
      Type: String
      Value: !Ref SNSEndpoint