AWSTemplateFormatVersion: "2010-09-09"
Description: "To enable access to S3 buckets from Private Subnet, using Lambda function"

Mappings: 
  vpc: 
    cidrblock: 
      ip: 172.20.1.0/16

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap ["vpc", "cidrblock", ip]
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: stack_vpc
          Value: test

  SSMVpc:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "VPC"
      Type: String
      Value: !Ref Vpc