AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaS3BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /LambdaS3BucketName

  WebS3BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /WebS3BucketName

Resources:
  PrivateEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "private-ec2-iam-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy # CWAgentで監視用ポリシー
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # SSMパラメータに書き込む用ポリシー
      Policies:
        - PolicyName: S3AndDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::{LambdaS3BucketName}
                  - !Sub arn:aws:s3:::{LambdaS3BucketName}/*
                  - !Sub arn:aws:s3:::{WebS3BucketName}
                  - !Sub arn:aws:s3:::{WebS3BucketName}/*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*
                # To monitor log using CloudWatch Agents
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:*:*:*"

  # SSM Parameter Store for role and instance profile
  SSMPrivateEC2InstanceRole:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "PrivateEC2InstanceIAMRole"
      Type: String
      Value: !Ref PrivateEC2Role
