AWSTemplateFormatVersion: "2010-09-09"
Description: "Create DynamoDB table"

Resources:
  Plan2DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "plan2-dynamodb-tbl"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true]
      # IAM permission
      

  Plan2DynamoDBTableSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "Plan2DynamoDBTable"
      Type: String
      Value: !Ref Plan2DynamoDBTable